### ISSUE TITLE
Request: add exec command

### ISSUE THREAD

**Issue by otbe** [AndiDittrich/NodeMCU-Tool#19]
Hi,

I really like nodemcu-tool, but one feature I really miss compared to nodemcu-uploader is the exec command. It will run a local file on my esp and exit.

Something like:
```
nodemcu-tool exec test.lua
```

Is this something you can add to nodemcu-tool?

Thanks!

**Comment by AndiDittrich** [comment]
The easiest way is to use a bash script like

``` bash
NMCU_BIN=node bin/nodemcu-tool.js

$NMCU_BIN upload $1
$NMCU_BIN run $1
```

but if you like, i can add an additional `--run` option (like the one used for the temrinal) to the upload command

**Comment by AndiDittrich** [comment]
implemented in **v3**
