### ISSUE TITLE
Cannot open remote file for write

### ISSUE THREAD

**Issue by curioussavage** [AndiDittrich/NodeMCU-Tool#22]
Hi thanks a million for this tool. I use it exclusively for uploading files to my wemos d1 minis.

I just flashed new firmware on my device with esptool and then use nodemcu-tool mkfs

I suspect this might be a symptom of an issue with that, either way it might be nice to add more detail/ suggestions to the error message if relevant. 

and of course if you have any idea how I can fix this much a appreciated
![espfail](https://cloud.githubusercontent.com/assets/7064600/21071920/a73ae9aa-be65-11e6-995c-38aa6f3e14b9.png)

here is the output.

**Comment by curioussavage** [comment]
As you should be able to see in the screen shot it creates the files on the device but writes nothing to them.

**Comment by curioussavage** [comment]
I tested in the terminal and was able to open and write to the empty file created by nodemcu-tool upload so it looks like it might be an issue with the lib and maybe the newest firmware?

**Comment by AndiDittrich** [comment]
Strange... i didn't test v1.5.4 yet
did you tried an earlier firmware version ? e.g. 1.5.1 ?

generally, there are no more details available... the fs.write function will only return false..

**Comment by AndiDittrich** [comment]
i can confirm the issue with NodeMCU Firmware **v1.5.4** - i will investigate the issue asap

**Comment by AndiDittrich** [comment]
should be fixed within the current master branch of NodeMCU-Tool
The team of NodeMCU LUA has changed the footprint of `file.open` within the last minor release...

Thank you very much for your report @curioussavage

**Comment by curioussavage** [comment]
That was fast! thanks for all your work on this.

**Comment by curioussavage** [comment]
I just successfully tested it on my machine.
