### ISSUE TITLE
TypeError: process.stdin.setRawMode is not a function

### ISSUE THREAD

**Issue by temp3l** [AndiDittrich/NodeMCU-Tool#23]
Hi,

I was trying to run this awesome tool from a bash inotifywait script.

and got:
```
nodemcu-tool/lib/SerialTerminal.js:53
            process.stdin.setRawMode(true);
                          ^

TypeError: process.stdin.setRawMode is not a function
```

I added this in line ~53

```
 if(process.stdin.isTTY) {
            process.stdin.setRawMode(true);
 }
```

**Comment by AndiDittrich** [comment]
Dear stephan,

thanks for your report. i will fix it asap.

btw. what is your use case for the `terminal` command in combination with a bash script ? i've never intended to use the terminal mode in this way ;)

best regards, Andi

**Comment by temp3l** [comment]
thank you!
i used it with a "file-changed"-watcher to auto upload after saving.
