### ISSUE TITLE
print that there are no files when there are no files

### ISSUE THREAD

**Issue by soldair** [AndiDittrich/NodeMCU-Tool#3]
also mentioned in #1 

when you have zero files it's not clear if the program just exited or you have an empty flash.
it would be nice to have a "no files found" message

**Comment by AndiDittrich** [comment]
i've added the feature to the current master/dev branch bf42203200577acca71e3dac82f34af15483e25a
the output will look like as follows:

### 3 Files

```
[NodeMCU-Tool] Connected
[NodeMCU] Version: 0.9.5 | ChipID: 0xd1aa | FlashID: 0x1640e0
[NodeMCU] Free Disk Space: 3330 KB | Total: 3346 KB | 3 Files
[NodeMCU] Files stored into Flash (SPIFFS)
          |- helloworld.lc (492 Bytes)
          |- README.md (13820 Bytes)
          |- helloworld.lua (382 Bytes)
```

### No Files

```
andi@sapphire:~/Development/IoT/NodeMCU-Tool$ ./bin/nodemcu-tool.js fsinfo
[NodeMCU-Tool] Connected
[NodeMCU] Version: 0.9.5 | ChipID: 0xd1aa | FlashID: 0x1640e0
[NodeMCU] Free Disk Space: 3346 KB | Total: 3346 KB | 0 Files
[NodeMCU] No Files found - do you have created the file-system ?
```

btw. you should take care of the exit codes - in case any unpredictable errors happened, a exit code > 0 will returned
