### ISSUE TITLE
Can i upload a * .INO file precompiled in BIN with this tool?

### ISSUE THREAD

**Issue by alejotima** [AndiDittrich/NodeMCU-Tool#30]
Hello dear developers

First of all, thank you very much for the great tool! I use it very well. I love!

I would like to know if I can upload a * .INO file precompiled in BIN with this tool, and if you can, you could give me an example.

Thank you.

**Comment by AndiDittrich** [comment]
Dear alejotima,

the datastream is hex-encoded and binary-safe. you can upload any kind of files. there are no special parameters required.

best regards, Andi
