### ISSUE TITLE
Option to connect via ip and port ("telnet")

### ISSUE THREAD

**Issue by Ognian** [AndiDittrich/NodeMCU-Tool#31]
Hi,
What do you think about adding a command line option to use ip and port ("telnet") to connect to a nodemcu allready connected to WLAN and running a "telnet" server? 
Thanks
 Ognian

**Comment by AndiDittrich** [comment]
Generally possible...but there are several "pseudo" telnet server for NodeMCU out there which are not "standard" telnet implementations - it causes some weird issues during authentication (username and/or password).

the optimal solution would be to create a dedecidated "file transfer service" for NodeMCU-Tool which did not rely on telnet
