### ISSUE TITLE
Code optimizing fails with multi-line commenting

### ISSUE THREAD

**Issue by T-vK** [AndiDittrich/NodeMCU-Tool#38]
I just uploaded a file with the optimize flag and then downloaded it again.  
What happened was basically this

``` Lua
local test = {
    --[[
    a = 123    
    ]]
}
```
turning into this:

``` Lua
local test = {
a = 123    
]]
}
```

So basically it looks like "optimizing" simply removes leading spaces, empty lines and lines starting with `--` and is not capable of understanding multi-line comments.  
I feel like the "optimizing" could use a lot of work in general. I mean it still leaves a ton of unnecessary white space, especially new line characters.  

Now the question is: Is the optimizing part of NodeMCU or is it part of this project.  

Well, in any case I would say we should probably start using something like [luamin](https://www.npmjs.com/package/luamin).

**Comment by AndiDittrich** [comment]
of course... its a very very simple [regex based script](https://github.com/AndiDittrich/NodeMCU-Tool/blob/master/lib/LuaOptimizer.js) which only removes whitespaces and single line comments. multi-line-comments are not impelmented yet.

if you like you can add multiline support. i didn't think that it is necessary to add real compression/optimizing libraries to the project
