### ISSUE TITLE
Not able to run the nodemcu-tool.js

### ISSUE THREAD

**Issue by Ankitr19** [AndiDittrich/NodeMCU-Tool#43]
![errorgit](https://user-images.githubusercontent.com/24638137/28555766-a22e9bf6-711f-11e7-8ea7-34c688423c55.png)
Please help!!

**Comment by AndiDittrich** [comment]
Hi Ankit,

this seems to be an issue with the [serialport](https://github.com/EmergingTechnologyAdvisors/node-serialport) package - not NodeMCU-Tool.

Please take a look onto their FAQs - in most cases such errors a caused by a missconfigured environment.
did you try to install the tool in the local folder instead of global scope ?

br, Andi

**Comment by Ankitr19** [comment]
Sir, now when I am trying to install it locally, i.e. just by cloning
the git repo and running the nodemcu-tool.js it is giving another
error.


On 7/25/17, Andi Dittrich <notifications@github.com> wrote:
> Hi Ankit,
>
> this seems to be an issue with the
> [serialport](https://github.com/EmergingTechnologyAdvisors/node-serialport)
> package - not NodeMCU-Tool.
>
> Please take a look onto their FAQs - in most cases such errors a caused by a
> missconfigured environment.
> did you try to install the tool in the local folder instead of global scope
> ?
>
> br, Andi
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AndiDittrich/NodeMCU-Tool/issues/43#issuecomment-317646070


-- 
Ankit Raj
Electronics and Communication Engineering
NIT Agartala
8414846511

**Comment by AndiDittrich** [comment]
in this case you have to run `npm install` to fetch the dependencies...

normally a simple `npm install nodemcu-tool` should do the job

**Comment by Ankitr19** [comment]
Sir a little query,  when I run npm isntall nodemcu-tool where it gets
install.  I mean where I can find the. js file to execute it?

Ankit Raj,
B. Tech,  Electronics and Communication  Engineering
NIT Agartala
8414846511

**Comment by AndiDittrich** [comment]
Please read the readme file first ;)

**in case you've cloned the github repo**
the "executable" file is located in `./bin/nodemcu-tool.js`
https://github.com/AndiDittrich/NodeMCU-Tool#as-archive-from-github

**in case of local npm installation**
the "executable" file is located in `./node_modules/nodemcu-tool/bin/nodemcu-tool.js`
https://github.com/AndiDittrich/NodeMCU-Tool#localproject-related-installation

**Comment by Ankitr19** [comment]
Yes, Sir, it worked. :)


On 7/25/17, Andi Dittrich <notifications@github.com> wrote:
> Please read the readme file first ;)
>
> **in case you've cloned the github repo**
> the "executable" file is located in `./bin/nodemcu-tool.js`
> https://github.com/AndiDittrich/NodeMCU-Tool#as-archive-from-github
>
> **in case of local npm installation**
> the "executable" file is located in
> `./node_modules/nodemcu-tool/bin/nodemcu-tool.js`
> https://github.com/AndiDittrich/NodeMCU-Tool#localproject-related-installation
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AndiDittrich/NodeMCU-Tool/issues/43#issuecomment-317651217


-- 
Ankit Raj
Electronics and Communication Engineering
NIT Agartala
8414846511
