### ISSUE TITLE
Failure to upload should result in a non-zero return code.

### ISSUE THREAD

**Issue by Willamin** [AndiDittrich/NodeMCU-Tool#48]
I frequently see the following error message:
```
[NodeMCU-Tool] Unable to establish connection - Timeout, no response detected - is NodeMCU online and the Lua interpreter ready ?
```

Because this error message always results in a `0` return code, I'm unable write a script to automatically retry.

**Comment by AndiDittrich** [comment]
i'll check this

**Comment by AndiDittrich** [comment]
i've added different return codes in NodeMCU-Tool **v3**

* **0** success
* **1** general error
* **127** low level serial communication error

please give it a try :)

**Comment by Willamin** [comment]
Thanks, @AndiDittrich! It looks good to me.
