### ISSUE TITLE
A little change for output-list of devices in json format.

### ISSUE THREAD

**Issue by johnnycubides** [AndiDittrich/NodeMCU-Tool#61]
https://github.com/AndiDittrich/NodeMCU-Tool/blob/19b3ec66e7d298438246adb4c11457e8406aaf34/lib/cli/nodemcu-tool.js#L327

Hello,
In line 327, I think that should be **serialDevices** instead **devices**; what do you think?

GNU/Linux Debian 10.
Before the change:
$ ./nodemcu-tool.js devices --json
[device]      ~ Cannot retrieve serial device list -
 
After the change
$ ./nodemcu-tool.js devices --json
[{"manufacturer":"Silicon Labs","serialNumber":"0001","pnpId":"usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0","vendorId":"10c4","productId":"ea60","comName":"/dev/ttyUSB1"},{"manufacturer":"Silicon Labs","serialNumber":"0001","pnpId":"usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0","vendorId":"10c4","productId":"ea60","comName":"/dev/ttyUSB0"}]

Regards Johnny Cubides.

**Comment by AndiDittrich** [comment]
Hi @johnnycubides ,

thanks for that hint, i will fix is asap
