### ISSUE TITLE
Support for NodeMCU-firmware 3.X

### ISSUE THREAD

**Issue by marcelstoer** [AndiDittrich/NodeMCU-Tool#65]
As per https://stackoverflow.com/a/57845719/131929 the latest NodeMCU 2.2.x -> 3.0 upgrade broke the `fetchDeviceInfo()` function. `node.info()` now works differently as per https://nodemcu.readthedocs.io/en/latest/modules/node/#nodeinfo.

**Comment by AndiDittrich** [comment]
Hi @marcelstoer ,

the issue seems only be related to the nodemcu-firmware >= 2.x.

i will check if it's possible to add some other kind of "detection"

**Comment by marcelstoer** [comment]
> the issue seems only be related to the nodemcu-firmware >= 2.x.

Yes. That's why I think the title of this issue is now wrong.

**Comment by AndiDittrich** [comment]
not really... nodemcu-firmware is on [2.2.1](https://github.com/nodemcu/nodemcu-firmware/releases) which causes the issue..

**Comment by marcelstoer** [comment]
We are both right - kind of. As I said we upgraded to SDK 3.0 i.e. we snapped our `dev` branch back to `master` just 2d ago.  However, the release tag and the notes are pending. Will have to do that later today. 

The issue described here is not present in 2.2.1 but only in 3.0 that is currently on `dev` and `master`.

**Comment by AndiDittrich** [comment]
ok sry my fault.

**Comment by AndiDittrich** [comment]
fixed within the master branch - projected for 3.1.0

**Comment by alset333** [comment]
Anticipated timeframe? This still seems to be unchanged in npm and trying to build is causing headaches personally.

**Comment by AndiDittrich** [comment]
i didn't noticed that there is a stable release of 3.x out - i'll release the changes asap

**Comment by AndiDittrich** [comment]
tagged 3.1.0 and published to npm
