### ISSUE TITLE
serialport bindings won't compile on modern Node

### ISSUE THREAD

**Issue by stuartpb** [AndiDittrich/NodeMCU-Tool#67]
#64 noted that the native code in the version of serialport used by this script isn't supported on versions of Node greater than 10: seeing as how the current LTS is v12, this dependency should really be updated.

**Comment by AndiDittrich** [comment]
the project currently uses serialport v7 - issue #64 affects serialport <= v6

**Comment by stuartpb** [comment]
Well, v7 doesn't compile on Node v13, so the dependency still needs an update. I've got a PR for this (bumping the semver with no code changes works) that I'll be submitting in a sec.

**Comment by AndiDittrich** [comment]
compatibility for serialport v8 / NodeJS 12 LTS has been added to the master branch

**Comment by AndiDittrich** [comment]
v3.2.0 is out including the changes
