### ISSUE TITLE
Execute arbitrary Lua statements

### ISSUE THREAD

**Issue by remcoder** [AndiDittrich/NodeMCU-Tool#8]
It would be a nice addition to be able to run a command like `node.restart()` via nodemcu-tool. 

For example: 
`nodemcu-tool --run-command "node.restart()"`

Executing commands like this via nodemcu-tool would allow be to easily write all sorts of bash scripts to support my dev cycle. Or is there already a way to do this?

**Comment by AndiDittrich** [comment]
Dear Remco,

such option is currently not available via the CLI but i can implement it. for basic commands like "restart" you can create a file like `restart.lua` with a special set of commands and run it directly:

``` bash
$ nodemcu-tool run restart.lua
```

best regards, Andi

**Comment by remcoder** [comment]
Hah, of course! :D Thanks for pointing that out.

I guess there's not really a need to implement anything extra then.

**Comment by remcoder** [comment]
Thanks for your work on nodemcu-tool btw. It really eases the dev flow with nodemcu. Keep up the good work! ;-)

**Comment by AndiDittrich** [comment]
ok & thanks!
