### ISSUE TITLE
No response detected - is NodeMCU online and the Lua interpreter ready ?

### ISSUE THREAD

**Issue by liurenqiu520** [AndiDittrich/NodeMCU-Tool#81]
## Checklist ##

1. Can you establish a serial connection **WITHOUT** Nodemcu-Tool - e.g. with a serial terminal like Putty ?  YES
2. Does the `nodemcu-tool fsinfo` command work ?  NO

-------------

## Environment ##

* **Operating System**  
  macOS 10.15.7
* **ESP Device/Revision**  
 ESP32-S2
* **NodeMCU-Tool Version**  
  `3.2.1`
* **Node.js Version**  
  `12.16`
* **NodeMCU LUA Firmware Version**  
  `dev-esp32` self compile

## Debug Output ##
➜  bros nodemcu-tool upload init.lua --debug --io-debug
[config]      ~ debug mode enabled 
[config]      ~ io-debug mode enabled - rx/tx messages are passed to logger 
[config]      ~ Project based configuration loaded 
[config]      ~ baudrate             = 115200 (type:string) 
[config]      ~ port                 = /dev/cu.usbserial-0001 (type:string) 
[config]      ~ connectionDelay      = 0 (type:number) 
[config]      ~ minify               = false (type:boolean) 
[config]      ~ compile              = false (type:boolean) 
[config]      ~ keeppath             = false (type:boolean) 
[config]      ~ remotename           = null (type:object) 
[config]      ~ run                  = false (type:boolean) 
[config]      ~ all                  = false (type:boolean) 
[config]      ~ json                 = false (type:boolean) 
[config]      ~ raw                  = false (type:boolean) 
[config]      ~ softreset            = false (type:boolean) 
[config]      ~ noninteractive       = false (type:boolean) 
[serialport]  ~ TX: print("echo1337")
[serialport]  ~ RX: �;32mI (57) boot: Partition Table:
I (60) boot: ## Label            Usage          Ty
[serialport]  ~ RX: pe ST Offset   Length[0[39m
[serialport]  ~ RX: m
I
[serialport]  ~ RX: (68) boot:
[serialport]  ~ RX: 0 nvs
[serialport]  ~ RX: WiF
[serialport]  ~ RX: i data
[serialport]  ~ RX: 01 02 000
[serialport]  ~ RX: 09000 00006
[serialport]  ~ RX: 000
[0[39m
[serialport]  ~ RX: ;32mI (75)
[serialport]  ~ RX: boot:  1 phy
[serialport]  ~ RX: _init
[serialport]  ~ RX: RF data
[serialport]  ~ RX: 01
[serialport]  ~ RX: 01 0000f000
[serialport]  ~ RX: 00001000[0[39m
[serialport]  ~ RX: m
I
[serialport]  ~ RX: (83) boot:
[serialport]  ~ RX: 2 factory
[serialport]  ~ RX: fact
[serialport]  ~ RX: ory app
[serialport]  ~ RX: 00 00 0001
[serialport]  ~ RX: 0000 001800
[serialport]  ~ RX: 00
[0;0[39m
[serialport]  ~ RX: 32mI (90) b
[serialport]  ~ RX: oot:  3 lfs
[serialport]  ~ RX: 
[serialport]  ~ RX: unknown
[serialport]  ~ RX: c2 0
[serialport]  ~ RX: 1 00190000 0
[serialport]  ~ RX: 0010000
[serialport]  ~ RX: I (
[serialport]  ~ RX: 97) boot:
[serialport]  ~ RX: 4 nodemcuspi
[serialport]  ~ RX: ffs    unkn
[serialport]  ~ RX: own
[serialport]  ~ RX: c2 00 001a
[serialport]  ~ RX: 0000 0007000
[serialport]  ~ RX: 0
[0;0[39m
[serialport]  ~ RX: 32mI (105) b
[serialport]  ~ RX: oot: End of
[serialport]  ~ RX: partition t
[serialport]  ~ RX: able
[[39m
[serialport]  ~ RX: 0;32mI (109
[serialport]  ~ RX: ) boot_comm:
[serialport]  ~ RX: chip revis
[serialport]  ~ RX: ion: 1, min
[serialport]  ~ RX: . applicatio
[serialport]  ~ RX: n chip revi
[serialport]  ~ RX: sion: 0
[serialport]  ~ RX: I (1
[serialport]  ~ RX: 16) esp_ima
[serialport]  ~ RX: ge: segment
[serialport]  ~ RX: 0: paddr=0x
[serialport]  ~ RX: 00010020 vad
[serialport]  ~ RX: dr=0x3f4000
[serialport]  ~ RX: 20 size=0x2c
[serialport]  ~ RX: 878 (182392
[serialport]  ~ RX: ) map
[serialport]  ~ RX: [39m
[serialport]  ~ RX: [0;3
[serialport]  ~ RX: 2mI (187) e
[serialport]  ~ RX: sp_image: se
[serialport]  ~ RX: gment 1: pa
[serialport]  ~ RX: ddr=0x0003c8
[serialport]  ~ RX: a0 vaddr=0x3
[serialport]  ~ RX: ffb0000 siz
[serialport]  ~ RX: e=0x03610 (
[serialport]  ~ RX: 13840) load
[serialport]  ~ RX: 
[0;32[39m
[serialport]  ~ RX: mI (193) es
[serialport]  ~ RX: p_image: seg
[serialport]  ~ RX: ment 2: pad
[serialport]  ~ RX: dr=0x0003fe
[serialport]  ~ RX: b8 vaddr=0x4
[serialport]  ~ RX: 0080000 size
[serialport]  ~ RX: =0x00158 (
[serialport]  ~ RX: 344) load[39m
[serialport]  ~ RX: [0m
[0;32[39m
[serialport]  ~ RX: mI (194) esp
[serialport]  ~ RX: _image: segm
[serialport]  ~ RX: ent 3: padd
[serialport]  ~ RX: r=0x0004001
[serialport]  ~ RX: 8 vaddr=0x40
[serialport]  ~ RX: 0d0018 size
[serialport]  ~ RX: =0xb5410 (74
[serialport]  ~ RX: 2416) map[[39m
[serialport]  ~ RX: 0m
[serialport]  ~ RX: [39m
[serialport]  ~ RX: [0;32mI (
[serialport]  ~ RX: 454) esp_ima
[serialport]  ~ RX: ge: segment
[serialport]  ~ RX: 4: paddr=0x
[serialport]  ~ RX: 000f5430 va
[serialport]  ~ RX: ddr=0x400801
[serialport]  ~ RX: 58 size=0x0
[serialport]  ~ RX: 02a8 (   680
[serialport]  ~ RX: ) load
[serialport]  ~ RX: I (4
[serialport]  ~ RX: 54) esp_ima
[serialport]  ~ RX: ge: segment
[serialport]  ~ RX: 5: paddr=0x
[serialport]  ~ RX: 000f56e0 vad
[serialport]  ~ RX: dr=0x4008040
[serialport]  ~ RX: 0 size=0x16
[serialport]  ~ RX: 188 ( 90504)
[serialport]  ~ RX: load
[serialport]  ~ RX: [39m
[serialport]  ~ RX: [0;32mI (
[serialport]  ~ RX: 496) esp_ima
[serialport]  ~ RX: ge: segment
[serialport]  ~ RX: 6: paddr=0x
[serialport]  ~ RX: 0010b870 va
[serialport]  ~ RX: ddr=0x400c00
[serialport]  ~ RX: 00 size=0x0
[serialport]  ~ RX: 0064 (   100
[serialport]  ~ RX: ) load
[serialport]  ~ RX: 
[serialport]  ~ RX: [39m
[serialport]  ~ RX: [0;32mI (
[serialport]  ~ RX: 510) boot:
[serialport]  ~ RX: Loaded app f
[serialport]  ~ RX: rom partiti
[serialport]  ~ RX: on at offset
[serialport]  ~ RX: 0x10000
[serialport]  ~ RX: I
[serialport]  ~ RX: (510) boot:
[serialport]  ~ RX: Disabling R
[serialport]  ~ RX: NG early en
[serialport]  ~ RX: tropy source
[serialport]  ~ RX: ...
[[39m
[serialport]  ~ RX: 0;32mI (510)
[serialport]  ~ RX: cpu_start:
[serialport]  ~ RX: Pro cpu up.
[serialport]  ~ RX: 
[0;32[39m
[serialport]  ~ RX: mI (514) cp
[serialport]  ~ RX: u_start: App
[serialport]  ~ RX: lication in
[serialport]  ~ RX: formation:[[39m
[serialport]  ~ RX: 0m

[serialport]  ~ RX: I (519) cpu_
[serialport]  ~ RX: start: Proj
[serialport]  ~ RX: ect name:
[serialport]  ~ RX: NodeMCU[[39m
[serialport]  ~ RX: 0m
I
[serialport]  ~ RX: (524) cpu_
[serialport]  ~ RX: start: App v
[serialport]  ~ RX: ersion:
[serialport]  ~ RX: 1.4.0-mast
[serialport]  ~ RX: er_20151229
[serialport]  ~ RX: -768-g7c07[[39m
[serialport]  ~ RX: 0m

[serialport]  ~ RX: I (531) cpu_
[serialport]  ~ RX: start: Comp
[serialport]  ~ RX: ile time:
[serialport]  ~ RX: Oct 11 20
[serialport]  ~ RX: 20 04:22:20[39m
[serialport]  ~ RX: [0m

[serialport]  ~ RX: I (537) cpu
[serialport]  ~ RX: _start: ELF
[serialport]  ~ RX: file SHA256
[serialport]  ~ RX: :  de0212e2e
[serialport]  ~ RX: 10978c2...[39m
[serialport]  ~ RX: [0m
[0;32[39m
[serialport]  ~ RX: mI (543) cpu
[serialport]  ~ RX: _start: ESP-
[serialport]  ~ RX: IDF:
[serialport]  ~ RX: v3.3.2-di
[serialport]  ~ RX: rty
[[39m
[serialport]  ~ RX: 0;32mI (548)
[serialport]  ~ RX: cpu_start:
[serialport]  ~ RX: Starting ap
[serialport]  ~ RX: p cpu, entr
[serialport]  ~ RX: y point is 0
[serialport]  ~ RX: x400813b4[[39m
[serialport]  ~ RX: 0m
I
[serialport]  ~ RX: (0) cpu_st
[serialport]  ~ RX: art: App cpu
[serialport]  ~ RX: up.
[[39m
[serialport]  ~ RX: 0;32mI (559
[serialport]  ~ RX: ) heap_init
[serialport]  ~ RX: : Initializi
[serialport]  ~ RX: ng. RAM ava
[serialport]  ~ RX: ilable for d
[serialport]  ~ RX: ynamic allo
[serialport]  ~ RX: cation:
[serialport]  ~ RX: I (5
[serialport]  ~ RX: 65) heap_in
[serialport]  ~ RX: it: At 3FFAE
[serialport]  ~ RX: 6E0 len 000
[serialport]  ~ RX: 01920 (6 KiB
[serialport]  ~ RX: ): DRAM
[serialport]  ~ RX: I
[serialport]  ~ RX: (572) heap_i
[serialport]  ~ RX: nit: At 3FFB
[serialport]  ~ RX: 9E68 len 00
[serialport]  ~ RX: 026198 (152
[serialport]  ~ RX: KiB): DRAM[39m
[serialport]  ~ RX: [0m

[serialport]  ~ RX: I (578) hea
[serialport]  ~ RX: p_init: At 3
[serialport]  ~ RX: FFE0440 len
[serialport]  ~ RX: 00003AE0 (1
[serialport]  ~ RX: 4 KiB): D/I
[serialport]  ~ RX: RAM
[0[39m
[serialport]  ~ RX: ;32mI (584)
[serialport]  ~ RX: heap_init:
[serialport]  ~ RX: At 3FFE4350
[serialport]  ~ RX: len 0001BCB
[serialport]  ~ RX: 0 (111 KiB):
[serialport]  ~ RX: D/IRAM
[serialport]  ~ RX: I (
[serialport]  ~ RX: 591) heap_i
[serialport]  ~ RX: nit: At 4009
[serialport]  ~ RX: 6588 len 00
[serialport]  ~ RX: 009A78 (38
[serialport]  ~ RX: KiB): IRAM[[39m
[serialport]  ~ RX: 0m
I
[serialport]  ~ RX: (597) cpu_
[serialport]  ~ RX: start: Pro c
[serialport]  ~ RX: pu start us
[serialport]  ~ RX: er code
[serialport]  ~ RX: 
[serialport]  ~ RX: [39m
[serialport]  ~ RX: [0;32mI (279
[serialport]  ~ RX: ) cpu_start
[serialport]  ~ RX: : Starting s
[serialport]  ~ RX: cheduler on
[serialport]  ~ RX: PRO CPU.[0[39m
[serialport]  ~ RX: m
I
[serialport]  ~ RX: (0) cpu_sta
[serialport]  ~ RX: rt: Startin
[serialport]  ~ RX: g scheduler
[serialport]  ~ RX: on APP CPU.
[serialport]  ~ RX: 
[serialport]  ~ RX: 
[serialport]  ~ RX: M
[serialport]  ~ RX: ounting flas
[serialport]  ~ RX: h filesyste
[serialport]  ~ RX: m...
[serialport]  ~ RX: N
[serialport]  ~ RX: o LFS image
[serialport]  ~ RX: loaded
[serialport]  ~ RX: I
[serialport]  ~ RX: (4
[serialport]  ~ RX: 20) wifi:wif
[serialport]  ~ RX: i driver ta
[serialport]  ~ RX: sk: 3ffc4c48
[serialport]  ~ RX: , prio:23,
[serialport]  ~ RX: stack:3584,
[serialport]  ~ RX: core=0
[0[39m
[serialport]  ~ RX: ;32mI (420)
[serialport]  ~ RX: system_api:
[serialport]  ~ RX: Base MAC ad
[serialport]  ~ RX: dress is no
[serialport]  ~ RX: t set, read
[serialport]  ~ RX: default base
[serialport]  ~ RX: MAC addres
[serialport]  ~ RX: s from BLK0
[serialport]  ~ RX: of EFUSE[0[39m
[serialport]  ~ RX: m
I
[serialport]  ~ RX: (420) syste
[serialport]  ~ RX: m_api: Base
[serialport]  ~ RX: MAC address
[serialport]  ~ RX: is not set,
[serialport]  ~ RX: read defau
[serialport]  ~ RX: lt base MAC
[serialport]  ~ RX: address fro
[serialport]  ~ RX: m BLK0 of EF
[serialport]  ~ RX: USE
[serialport]  ~ RX: I
[serialport]  ~ RX: (
[serialport]  ~ RX: 450) wifi:w
[serialport]  ~ RX: ifi firmware
[serialport]  ~ RX: version: 4
[serialport]  ~ RX: 4aa95c
I (4
[serialport]  ~ RX: 50) wifi:co
[serialport]  ~ RX: nfig NVS fla
[serialport]  ~ RX: sh: enabled
[serialport]  ~ RX: I (450) wi
[serialport]  ~ RX: fi:config n
[serialport]  ~ RX: ano formatin
[serialport]  ~ RX: g: disabled
[serialport]  ~ RX: I (450) wi
[serialport]  ~ RX: fi:Init dyn
[serialport]  ~ RX: amic tx buff
[serialport]  ~ RX: er num: 32
[serialport]  ~ RX: I (460) wif
[serialport]  ~ RX: i:Init data
[serialport]  ~ RX: frame dynam
[serialport]  ~ RX: ic rx buffe
[serialport]  ~ RX: r num: 32
I
[serialport]  ~ RX: (460) wifi:
[serialport]  ~ RX: Init manage
[serialport]  ~ RX: ment frame d
[serialport]  ~ RX: ynamic rx b
[serialport]  ~ RX: uffer num: 3
[serialport]  ~ RX: 2
I (470)
[serialport]  ~ RX: wifi:Init ma
[serialport]  ~ RX: nagement sh
[serialport]  ~ RX: ort buffer n
[serialport]  ~ RX: um: 32
I (
[serialport]  ~ RX: 470) wifi:In
[serialport]  ~ RX: it static r
[serialport]  ~ RX: x buffer siz
[serialport]  ~ RX: e: 1600
I
[serialport]  ~ RX: (480) wifi:I
[serialport]  ~ RX: nit static r
[serialport]  ~ RX: x buffer nu
[serialport]  ~ RX: m: 10
I (4
[serialport]  ~ RX: 80) wifi:Ini
[serialport]  ~ RX: t dynamic r
[serialport]  ~ RX: x buffer num
[serialport]  ~ RX: : 32

Nod
[serialport]  ~ RX: eMCU ESP32 b
[serialport]  ~ RX: uilt with D
[serialport]  ~ RX: ocker provid
[serialport]  ~ RX: ed by fright
[serialport]  ~ RX: anic.com
[serialport]  ~ RX: branch: dev-
[serialport]  ~ RX: esp32
        com
[serialport]  ~ RX: mit: 7c07f91
[serialport]  ~ RX: 4836d73e22e
[serialport]  ~ RX: 862c149def8b
[serialport]  ~ RX: 3314b77e43
[serialport]  ~ RX: SSL: true
[serialport]  ~ RX: modules:
[serialport]  ~ RX: -
 build cr
[serialport]  ~ RX: eated on 20
[serialport]  ~ RX: 20-10-11 02:
[serialport]  ~ RX: 58
 powere
[serialport]  ~ RX: d by Lua 5.1
[serialport]  ~ RX: .4 on ESP-ID
[serialport]  ~ RX: F -9e7082 o
[serialport]  ~ RX: n ESP-IDF -
[serialport]  ~ RX: 9e7082 on ES
[serialport]  ~ RX: P-IDF -9e70
[serialport]  ~ RX: 82 on ESP-ID
[serialport]  ~ RX: F -9e7082 o
[serialport]  ~ RX: n ESP-IDF -9
[serialport]  ~ RX: e7082 on SDK
[serialport]  ~ RX: IDF
[serialport]  ~ RX: [39m
[serialport]  ~ RX: [0;32m
[serialport]  ~ RX: I (610) phy
[serialport]  ~ RX: : phy_versio
[serialport]  ~ RX: n: 4180, cb
[serialport]  ~ RX: 3948e, Sep 1
[serialport]  ~ RX: 2 2019, 16:3
[serialport]  ~ RX: 9:13, 0, 0[39m
[serialport]  ~ RX: [0m
I (620)
[serialport]  ~ RX: wifi:mode
[serialport]  ~ RX: : sta (40:f
[serialport]  ~ RX: 5:20:78:79:8
[serialport]  ~ RX: c)
>
[connector]   ~ Echo: �;32mI (57) boot: Partition Table:
[connector]   ~ Response: I (60) boot: ## Label            Usage          Type ST Offset   Length
I (68) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (75) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (83) boot:  2 factory          factory app      00 00 00010000 00180000
I (90) boot:  3 lfs              unknown          c2 01 00190000 00010000
I (97) boot:  4 nodemcuspiffs    unknown          c2 00 001a0000 00070000
I (105) boot: End of partition table
I (109) boot_comm: chip revision: 1, min. application chip revision: 0
I (116) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x2c878 (182392) map
I (187) esp_image: segment 1: paddr=0x0003c8a0 vaddr=0x3ffb0000 size=0x03610 ( 13840) load
I (193) esp_image: segment 2: paddr=0x0003feb8 vaddr=0x40080000 size=0x00158 (   344) load
I (194) esp_image: segment 3: paddr=0x00040018 vaddr=0x400d0018 size=0xb5410 (742416) map
I (454) esp_image: segment 4: paddr=0x000f5430 vaddr=0x40080158 size=0x002a8 (   680) load
I (454) esp_image: segment 5: paddr=0x000f56e0 vaddr=0x40080400 size=0x16188 ( 90504) load
I (496) esp_image: segment 6: paddr=0x0010b870 vaddr=0x400c0000 size=0x00064 (   100) load
I (510) boot: Loaded app from partition at offset 0x10000
I (510) boot: Disabling RNG early entropy source...
I (510) cpu_start: Pro cpu up.
I (514) cpu_start: Application information:
I (519) cpu_start: Project name:     NodeMCU
I (524) cpu_start: App version:      1.4.0-master_20151229-768-g7c07
I (531) cpu_start: Compile time:     Oct 11 2020 04:22:20
I (537) cpu_start: ELF file SHA256:  de0212e2e10978c2...
I (543) cpu_start: ESP-IDF:          v3.3.2-dirty
I (548) cpu_start: Starting app cpu, entry point is 0x400813b4
I (0) cpu_start: App cpu up.
I (559) heap_init: Initializing. RAM available for dynamic allocation:
I (565) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (572) heap_init: At 3FFB9E68 len 00026198 (152 KiB): DRAM
I (578) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (584) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (591) heap_init: At 40096588 len 00009A78 (38 KiB): IRAM
I (597) cpu_start: Pro cpu start user code
I (279) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.

Mounting flash filesystem...
No LFS image loaded
I (420) wifi:wifi driver task: 3ffc4c48, prio:23, stack:3584, core=0
I (420) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (420) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (450) wifi:wifi firmware version: 44aa95c
I (450) wifi:config NVS flash: enabled
I (450) wifi:config nano formating: disabled
I (450) wifi:Init dynamic tx buffer num: 32
I (460) wifi:Init data frame dynamic rx buffer num: 32
I (460) wifi:Init management frame dynamic rx buffer num: 32
I (470) wifi:Init management short buffer num: 32
I (470) wifi:Init static rx buffer size: 1600
I (480) wifi:Init static rx buffer num: 10
I (480) wifi:Init dynamic rx buffer num: 32

NodeMCU ESP32 built with Docker provided by frightanic.com
        branch: dev-esp32
        commit: 7c07f914836d73e22e862c149def8b3314b77e43
        SSL: true
        modules: -
 build created on 2020-10-11 02:58
 powered by Lua 5.1.4 on ESP-IDF -9e7082 on ESP-IDF -9e7082 on ESP-IDF -9e7082 on ESP-IDF -9e7082 on ESP-IDF -9e7082 on SDK IDF
I (610) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0
I (620) wifi:mode : sta (40:f5:20:78:79:8c)
[NodeMCU-Tool]~ Unable to establish connection 
[NodeMCU-Tool]~ No response detected - is NodeMCU online and the Lua interpreter ready ? 
[NodeMCU-Tool]~ Error: No response detected - is NodeMCU online and the Lua interpreter ready ?
    at /usr/local/lib/node_modules/nodemcu-tool/lib/connector/check-connection.js:28:28

**Comment by AndiDittrich** [comment]
please fix your initial issue (point 1) - if the connection is not working the issue is not related to NodeMCU Tool

**Comment by liurenqiu520** [comment]
> please fix your initial issue (point 1) - if the connection is not working the issue is not related to NodeMCU Tool

YES, i can use ESPlorer connect

**Comment by AndiDittrich** [comment]
did you read about the reset-on-connect issue ?

**Comment by liurenqiu520** [comment]
thx, i got it

**Comment by HHHartmann** [comment]
Btw. ESP32-S2 is a different chip which currently is not supported by nodemcu firmware
