### ISSUE TITLE
is NodeMCU online and the Lua interpreter ready ?

### ISSUE THREAD

**Issue by ellenfel** [AndiDittrich/NodeMCU-Tool#90]
I am running this tool on ubuntu16.04 
and iam currently following instructions from:
https://github.com/nodemcu/nodemcu-firmware/blob/release/docs/getting-started.md#nodemcu-tool

after  installing  NodeMCU-Tool globally with `$ npm install nodemcu-tool -g` 
running `$ nodemcu-tool --version` gives `3.2.1` so i assume installation was successful but when i try to upload a lua file
`$ nodemcu-tool upload --port=/dev/ttyUSB0 helloworld.l`,

`[NodeMCU-Tool]~ Unable to establish connection` 
`[NodeMCU-Tool]~ Timeout, no response detected - is NodeMCU online and the Lua interpreter ready ?`
error messages returns.

`$ nodemcu-tool devices` returns
`(node:18906) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency`
`(Use node --trace-warnings ... to show where the warning was created)`
`[device]      ~ Device filter is active - only known NodeMCU devices (USB vendor-id) will be listed.`
`[device]      ~ Connected Devices | Total: 1`
`[device]      ~ - /dev/ttyUSB0 (1a86, usb-1a86_USB2.0-Ser_-if00-port0)`

This issue has opend here before in  : https://github.com/AndiDittrich/NodeMCU-Tool/issues/25
and the solution was:  `$ nodemcu-tool mkfs  --connection-delay 1000`
but unfortunattly this just returns the same error that returns when i try to upload a lua file.

**Comment by AndiDittrich** [comment]
Hi @ellenfel ,

the issue template contains some questions / required debug informations. please check them first as well as the docs related to https://github.com/AndiDittrich/NodeMCU-Tool/blob/master/docs/Reset_on_Connect.md
